INFO 2022-01-19 23:29:48 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:29:48 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2022-01-19 23:29:48 FaceAlignModelLoader.py: 17] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2022-01-19 23:29:48 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:29:49 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2022-01-19 23:29:49 FaceRecModelLoader.py: 17] Start to analyze the face recognition model, model path: models, model category: face_recognition，model name: face_recognition_1.0
INFO 2022-01-19 23:29:49 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:29:49 FaceRecModelLoader.py: 31] Successfully loaded the face recognition model!
INFO 2022-01-19 23:31:23 FaceDetModelLoader.py: 17] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-01-19 23:31:23 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:31:23 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2022-01-19 23:31:23 FaceAlignModelLoader.py: 17] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2022-01-19 23:31:23 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:31:24 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2022-01-19 23:31:24 FaceRecModelLoader.py: 17] Start to analyze the face recognition model, model path: models, model category: face_recognition，model name: face_recognition_1.0
INFO 2022-01-19 23:31:24 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:31:24 FaceRecModelLoader.py: 31] Successfully loaded the face recognition model!
INFO 2022-01-19 23:36:02 FaceDetModelLoader.py: 17] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-01-19 23:36:02 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:36:02 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2022-01-19 23:36:02 FaceAlignModelLoader.py: 17] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2022-01-19 23:36:02 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:36:03 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2022-01-19 23:36:03 FaceRecModelLoader.py: 17] Start to analyze the face recognition model, model path: models, model category: face_recognition，model name: face_recognition_1.0
INFO 2022-01-19 23:36:03 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:36:03 FaceRecModelLoader.py: 31] Successfully loaded the face recognition model!
INFO 2022-01-19 23:54:44 FaceDetModelLoader.py: 17] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-01-19 23:54:44 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:54:44 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2022-01-19 23:54:44 FaceAlignModelLoader.py: 17] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2022-01-19 23:54:44 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:54:45 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2022-01-19 23:54:45 FaceRecModelLoader.py: 17] Start to analyze the face recognition model, model path: models, model category: face_recognition，model name: face_recognition_1.0
INFO 2022-01-19 23:54:45 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-19 23:54:46 FaceRecModelLoader.py: 31] Successfully loaded the face recognition model!
INFO 2022-01-20 00:13:28 FaceDetModelLoader.py: 17] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-01-20 00:13:28 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:13:28 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2022-01-20 00:13:28 FaceAlignModelLoader.py: 17] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2022-01-20 00:13:28 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:13:29 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2022-01-20 00:13:29 FaceRecModelLoader.py: 17] Start to analyze the face recognition model, model path: models, model category: face_recognition，model name: face_recognition_1.0
INFO 2022-01-20 00:13:29 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:13:29 FaceRecModelLoader.py: 31] Successfully loaded the face recognition model!
INFO 2022-01-20 00:16:02 FaceDetModelLoader.py: 17] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-01-20 00:16:02 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:16:02 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2022-01-20 00:16:02 FaceAlignModelLoader.py: 17] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2022-01-20 00:16:02 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:16:02 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2022-01-20 00:16:02 FaceRecModelLoader.py: 17] Start to analyze the face recognition model, model path: models, model category: face_recognition，model name: face_recognition_1.0
INFO 2022-01-20 00:16:02 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:16:02 FaceRecModelLoader.py: 31] Successfully loaded the face recognition model!
INFO 2022-01-20 00:24:28 FaceDetModelLoader.py: 17] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-01-20 00:24:28 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:24:28 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2022-01-20 00:24:28 FaceAlignModelLoader.py: 17] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2022-01-20 00:24:28 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:24:29 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2022-01-20 00:24:29 FaceRecModelLoader.py: 17] Start to analyze the face recognition model, model path: models, model category: face_recognition，model name: face_recognition_1.0
INFO 2022-01-20 00:24:29 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:24:29 FaceRecModelLoader.py: 31] Successfully loaded the face recognition model!
ERROR 2022-01-20 00:28:17 app.py: 1753] Exception on /video [GET]
Traceback (most recent call last):
  File "C:\Users\PC\PycharmProjects\facenet-realtime-face-recognition\venv\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\PC\PycharmProjects\facenet-realtime-face-recognition\venv\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\PC\PycharmProjects\facenet-realtime-face-recognition\venv\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\PC\PycharmProjects\facenet-realtime-face-recognition\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\PC\PycharmProjects\facenet-realtime-face-recognition\venv\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PC\PycharmProjects\facenet-realtime-face-recognition\venv\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 404, in video
    return Response(generate_frames(),mimetype='multipart/x-mixed-replace; boundary=frame')
TypeError: generate_frames() missing 5 required positional arguments: 'faceDetModelHandler', 'faceAlignModelHandler', 'faceRecModelHandler', 'face_cropper', and 'embedding_dict'
INFO 2022-01-20 00:29:46 FaceDetModelLoader.py: 17] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-01-20 00:29:46 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2022-01-20 00:29:46 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
